version: "3.7"


services:
  client:
    build: ./client
    depends_on:
      - "server"
    ports:
      - "3000:3000"

  server:
    build: ./server
    depends_on:
      - "db"
    ports:
      - "5000:5000"
      - "5551:5551"

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pongmania:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}


volumes:
  pongmania: 