version: "3.7"


services:
  client:
    build: ./client
    depends_on:
      - "server"
    ports:
      - "3000:3000"

  server:
    build: ./server
    depends_on:
      - "db"
    ports:
      - "5000:5000"
      - "5551:5551"

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pongmania:/var/lib/postgresql/data
      # - ./server/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_USER=Conanyedo
      - POSTGRES_PASSWORD=pongmania
      - POSTGRES_DB=pongmania
      - TZ=GMT-1


volumes:
  pongmania: 